// This file is auto-generated by TanStack Router - placeholder
// Lovable will overwrite this on next build
import { createRootRoute, createRouter } from '@tanstack/react-router'

const rootRoute = createRootRoute()

export const routeTree = rootRoute.addChildren([])

export const router = createRouter({
  routeTree,
})
